# Generated by Django 2.2.2 on 2019-07-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedatos', '0004_auto_20190705_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bienesyservicios',
            name='imgc',
            field=models.ImageField(default=None, null=True, upload_to='bysimg'),
        ),
    ]
