# Generated by Django 2.2.2 on 2019-08-07 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basedatos', '0005_auto_20190708_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('idh', models.AutoField(primary_key=True, serialize=False)),
                ('fechh', models.DateField(verbose_name='Fecha de consulta')),
                ('monto', models.DecimalField(decimal_places=3, max_digits=15)),
            ],
        ),
        migrations.AlterField(
            model_name='bienesyservicios',
            name='precio',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('idr', models.AutoField(primary_key=True, serialize=False)),
                ('momp', models.DecimalField(decimal_places=3, max_digits=15)),
                ('cant', models.PositiveIntegerField()),
                ('idbs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basedatos.Bienesyservicios')),
                ('idh', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basedatos.Historial')),
            ],
        ),
    ]
