# Generated by Django 2.2.2 on 2019-08-07 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedatos', '0006_auto_20190807_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='bienesyservicios',
            name='umed',
            field=models.TextField(default=2, max_length=250, verbose_name='Unidad de medida'),
            preserve_default=False,
        ),
    ]
